Repository sustainability-suite/sustainability-odoo, pull requests merged in 2025-03, with the labels that each got.

#342 [ADD] sustainability_employee_commuting: remote work contract dates test
  sustainability_employee_commuting/tests/common.py
  sustainability_employee_commuting/tests/test_commuting.py
Labels: test, needs review

#369 [ADD] sustainability: add test tour for create journal entry
  sustainability/__manifest__.py
  sustainability/static/src/js/tours/create_journal_entry.js
  sustainability/tests/__init__.py
  sustainability/tests/test_tour.py
Labels: bot is merging ⏳, needs review

#363 [FIX] sustainability: Add models description
  sustainability/models/carbon_copy_mixin.py
  sustainability/models/carbon_distribution_line.py
  sustainability/models/carbon_factor_value.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_line_origin.py
  sustainability/models/sustainability_action_plan.py
  sustainability/models/sustainability_approach.py
  sustainability/models/sustainability_nomenclature.py
Labels: bot is merging ⏳, needs review

#361 [FIX] sustainability: Add string in order to not raise warning when installing
  sustainability/models/carbon_factor.py
Labels: bot is merging ⏳, needs review

#367 [FIX] sustainability: Add conversion tests back and fix them
  sustainability/tests/__init__.py
  sustainability/tests/test_conversion.py
Labels: bot is merging ⏳, needs review

#366 [FIX] sustainability: Fix TODO in tests. Add a tests previously written
  sustainability_purchase/tests/test_purchase.py
Labels: bot is merging ⏳, needs review

#370 [IMP] sustainability: filter product ef by uom
  sustainability/models/carbon_mixin.py
  sustainability/models/product_product.py
  sustainability/models/product_supplierinfo.py
  sustainability/models/product_template.py
  sustainability/tests/__init__.py
  sustainability/tests/test_factor_domain.py
Labels: bot is merging ⏳, needs review

#368 [FIX] sustainability: Extract carbon move_type to external method for easier testing and add unit tests
  sustainability/models/account_move_line.py
  sustainability/tests/__init__.py
  sustainability/tests/test_account_move.py
Labels: bot is merging ⏳, needs review

#380 [16.0][FW] sustainability: multiple ports from 17.0
  sustainability/models/account_move_line.py
  sustainability/models/carbon_copy_mixin.py
  sustainability/models/carbon_distribution_line.py
  sustainability/models/carbon_factor.py
  sustainability/models/carbon_factor_value.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_line_origin.py
  sustainability/models/sustainability_action_plan.py
  sustainability/models/sustainability_approach.py
  sustainability/models/sustainability_nomenclature.py
  sustainability/tests/__init__.py
  sustainability/tests/test_account_move.py
  sustainability/tests/test_conversion.py
  sustainability/views/account_account.xml
  sustainability/views/account_move.xml
  sustainability/views/carbon_line_origin.xml
  sustainability/views/product_category.xml
  sustainability/views/product_template.xml
  sustainability/views/res_country.xml
  sustainability_purchase/views/res_partner.xml
Labels: bot is merging ⏳, needs review

#371 [IMP] sustainability_stock: implement cache climatiq api
  sustainability/data/menu_items.xml
  sustainability/models/carbon_common_mixin.py
  sustainability/models/carbon_factor.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/res_config_settings.py
  sustainability/tests/test_action.py
  sustainability/views/res_config_settings.xml
  sustainability_stock/README.rst
  sustainability_stock/__init__.py
  sustainability_stock/__manifest__.py
  sustainability_stock/data/menu_items.xml
  sustainability_stock/models/__init__.py
  sustainability_stock/models/account_move.py
  sustainability_stock/models/carbon_line_mixin.py
  sustainability_stock/models/carbon_line_origin.py
  sustainability_stock/models/res_company.py
  sustainability_stock/models/res_config_settings.py
  sustainability_stock/models/res_partner.py
  sustainability_stock/models/stock_picking.py
  sustainability_stock/models/sustainability_stock_freight_computation.py
  sustainability_stock/pyproject.toml
  sustainability_stock/readme/CONTRIBUTORS.rst
  sustainability_stock/readme/DESCRIPTION.rst
  sustainability_stock/security/ir.model.access.csv
  sustainability_stock/static/description/index.html
  sustainability_stock/tests/__init__.py
  sustainability_stock/tests/common.py
  sustainability_stock/tests/test_stock.py
  sustainability_stock/views/carbon_line_origin.xml
  sustainability_stock/views/res_config_settings.xml
  sustainability_stock/views/res_partner.xml
  sustainability_stock/views/stock_picking.xml
  sustainability_stock/views/sustainability_stock_freight_computation.xml
Labels: bot is merging ⏳, needs review

#394 [18.0][FW] [FIX][#335] sustainability: Fix every ensure_one on carbon_mixin
  sustainability/models/carbon_mixin.py
Labels: bot is merging ⏳, needs review

#383 [16.0][FW] [IMP] sustainability_stock: implement cache climatiq api
  setup/sustainability_stock/odoo/addons/sustainability_stock
  setup/sustainability_stock/setup.py
  sustainability/data/menu_items.xml
  sustainability/models/carbon_common_mixin.py
  sustainability/models/carbon_factor.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/res_config_settings.py
  sustainability/tests/test_action.py
  sustainability/views/res_config_settings.xml
  sustainability_stock/README.rst
  sustainability_stock/__init__.py
  sustainability_stock/__manifest__.py
  sustainability_stock/data/menu_items.xml
  sustainability_stock/models/__init__.py
  sustainability_stock/models/account_move.py
  sustainability_stock/models/carbon_line_mixin.py
  sustainability_stock/models/carbon_line_origin.py
  sustainability_stock/models/res_company.py
  sustainability_stock/models/res_config_settings.py
  sustainability_stock/models/res_partner.py
  sustainability_stock/models/stock_picking.py
  sustainability_stock/models/sustainability_stock_freight_computation.py
  sustainability_stock/pyproject.toml
  sustainability_stock/readme/CONTRIBUTORS.rst
  sustainability_stock/readme/DESCRIPTION.rst
  sustainability_stock/security/ir.model.access.csv
  sustainability_stock/static/description/index.html
  sustainability_stock/tests/__init__.py
  sustainability_stock/tests/common.py
  sustainability_stock/tests/test_stock.py
  sustainability_stock/views/carbon_line_origin.xml
  sustainability_stock/views/res_config_settings.xml
  sustainability_stock/views/res_partner.xml
  sustainability_stock/views/stock_picking.xml
  sustainability_stock/views/sustainability_stock_freight_computation.xml
Labels: approved, bot is merging ⏳, needs review
