Repository sustainability-suite/sustainability-odoo, pull requests merged in 2025-01, with the labels that each got.

#236 [16.0][BACKPORT] sustainability*: add fr translation
  sustainability/i18n/fr.po
  sustainability_account_asset_management/i18n/fr.po
  sustainability_employee_commuting/i18n/fr.po
  sustainability_hr_expense_report/i18n/fr.po
  sustainability_mis_builder/i18n/fr.po
  sustainability_purchase/i18n/fr.po
Labels: bot is merging ⏳

#235 [17.0][IMP] sustainability*: add fr translation
  sustainability/i18n/fr.po
  sustainability_account_asset_management/i18n/fr.po
  sustainability_employee_commuting/i18n/fr.po
  sustainability_hr_expense_report/i18n/fr.po
  sustainability_mis_builder/i18n/fr.po
  sustainability_point_of_sale/i18n/fr.po
  sustainability_product_label_print/i18n/fr.po
  sustainability_purchase/i18n/fr.po
  sustainability_website_sale/i18n/fr.po
Labels: bot is merging ⏳

#234 [17.0][FIX] sustainability_hr_expense_report: return False if no account
  sustainability_hr_expense_report/models/hr_expense.py
Labels: bot is merging ⏳

#238 [IMP] sustainability: add openupgradelib requirement
  requirements.txt
  sustainability/__manifest__.py
Labels: bot is merging ⏳, needs review

#223 [ADD] sustainability_purchase: product's supplier emission factor preceding order
  sustainability/__manifest__.py
  sustainability/models/__init__.py
  sustainability/models/account_move_line.py
  sustainability/models/carbon_factor.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_mixin.py
  sustainability/models/product_supplierinfo.py
  sustainability/models/res_partner.py
  sustainability/tests/__init__.py
  sustainability/tests/common.py
  sustainability/tests/test_action.py
  sustainability/tests/test_vendors_bill.py
  sustainability/views/product_supplierinfo.xml
  sustainability_purchase/__manifest__.py
  sustainability_purchase/models/__init__.py
  sustainability_purchase/models/account_move_line.py
  sustainability_purchase/models/carbon_factor.py
  sustainability_purchase/models/product_supplierinfo.py
  sustainability_purchase/models/purchase_order_line.py
  sustainability_purchase/tests/__init__.py
  sustainability_purchase/tests/common.py
  sustainability_purchase/tests/test_purchase.py
  sustainability_purchase/views/carbon_factor.xml
  sustainability_purchase/views/product_supplierinfo.xml
Labels: enhancement, bot is merging ⏳, needs review
