Repository sustainability-suite/sustainability-odoo, pull requests merged in 2025-02, with the labels that each got.

#244 [IMP] sustainability: validity date tests
  sustainability/tests/__init__.py
  sustainability/tests/common.py
  sustainability/tests/test_carbon_computation.py
  sustainability/tests/test_conversion.py
Labels: test, needs review

#241 [IMP] sustainability: Add test for uncertainity computation
  sustainability/models/carbon_factor.py
  sustainability/tests/__init__.py
  sustainability/tests/test_uncertainty.py
Labels: needs review

#245 [IMP] sustainability: test preceeding order
  sustainability/tests/__init__.py
  sustainability/tests/common.py
  sustainability/tests/test_carbon_computation.py
  sustainability/tests/test_conversion.py
  sustainability/tests/test_preceeding_order.py
Labels: test, needs review

#266 [ADD] sustainability_employee_commuting: remote work management
  sustainability_employee_commuting/README.rst
  sustainability_employee_commuting/__manifest__.py
  sustainability_employee_commuting/data/demo.xml
  sustainability_employee_commuting/data/ir_cron.xml
  sustainability_employee_commuting/models/account_move.py
  sustainability_employee_commuting/models/hr_employee.py
  sustainability_employee_commuting/models/res_company.py
  sustainability_employee_commuting/models/res_config_settings.py
  sustainability_employee_commuting/static/description/index.html
  sustainability_employee_commuting/tests/__init__.py
  sustainability_employee_commuting/tests/common.py
  sustainability_employee_commuting/tests/test_commuting.py
  sustainability_employee_commuting/views/res_config_settings.xml
Labels: enhancement, bot is merging ⏳, needs review

#242 [IMP] sustainability_employee_commuting: Allow user to select if he want to post his account move. Add UserError
  sustainability_employee_commuting/data/demo.xml
  sustainability_employee_commuting/models/res_company.py
  sustainability_employee_commuting/models/res_config_settings.py
  sustainability_employee_commuting/views/res_config_settings.xml
Labels: bot is merging ⏳, needs review

#281 [18.0][MIG] sustainability_purchase: Migration
  sustainability_purchase/README.rst
  sustainability_purchase/__init__.py
  sustainability_purchase/__manifest__.py
  sustainability_purchase/data/demo.xml
  sustainability_purchase/data/ir_cron.xml
  sustainability_purchase/i18n/fr.po
  sustainability_purchase/i18n/sustainability_purchase.pot
  sustainability_purchase/models/__init__.py
  sustainability_purchase/models/carbon_line_origin.py
  sustainability_purchase/models/product_template.py
  sustainability_purchase/models/purchase_order.py
  sustainability_purchase/models/purchase_order_line.py
  sustainability_purchase/pyproject.toml
  sustainability_purchase/readme/CONTRIBUTORS.rst
  sustainability_purchase/readme/DESCRIPTION.rst
  sustainability_purchase/static/description/index.html
  sustainability_purchase/tests/__init__.py
  sustainability_purchase/tests/common.py
  sustainability_purchase/tests/test_purchase.py
  sustainability_purchase/views/carbon_factor.xml
  sustainability_purchase/views/carbon_line_origin.xml
  sustainability_purchase/views/purchase_order.xml
  sustainability_purchase/views/purchase_supplierinfo.xml
  sustainability_purchase/views/res_partner.xml
Labels: bot is merging ⏳, needs review

#298 [ADD] sustainability: emission factors by weight for storable products
  sustainability/models/account_move_line.py
  sustainability/models/carbon_factor.py
  sustainability_purchase/models/purchase_order_line.py
Labels: enhancement, approved, bot is merging ⏳, needs review

#305 [FIX] sustainability: tests preceeding order
  sustainability/tests/test_preceeding_order.py
Labels: test, approved, bot is merging ⏳, needs review

#275 [IMP] pull request template
  .github/pull_request_template.md
Labels: documentation, approved, ready to merge, needs review

#307 [CI] fix
  .github/workflows/update_pot.yaml
Labels: needs review

#309 [CI] use correct token
  .copier-answers.yml
  .github/workflows/test.yml
  .github/workflows/update_pot.yaml
Labels: bot is merging ⏳, needs review

#311 [CI] use correct token
  .github/workflows/test.yml
Labels: needs review

#310 [CI] use correct token
  .github/workflows/test.yml
Labels: needs review

#314 [IMP] sustainability: add tests for carbon factor by weight calculation
  sustainability/tests/__init__.py
  sustainability/tests/test_ef_by_weight.py
Labels: test, needs review

#312 [18.0][FW] sustainability: multiple ports from 17.0
  .oca/oca-port/blacklist/sustainability.json
  sustainability/models/account_move_line.py
  sustainability/models/carbon_factor.py
  sustainability/tests/test_preceeding_order.py
  sustainability_purchase/models/purchase_order_line.py
Labels: bot is merging ⏳, needs review

#313 [16.0][BP] sustainability: emission factors by weight for storable products
  .oca/oca-port/blacklist/sustainability.json
  sustainability/models/account_move_line.py
  sustainability/models/carbon_factor.py
  sustainability_purchase/models/purchase_order_line.py
Labels: bot is merging ⏳, needs review

#324 [PERF] sustainability*: improve performance
  sustainability/models/account_move_line.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_line_origin.py
  sustainability/models/carbon_mixin.py
  sustainability_hr_expense_report/models/hr_expense.py
  sustainability_purchase/models/purchase_order_line.py
Labels: approved, bot is merging ⏳, needs review

#323 [IMP] sustainability: Add product_id to clo
  sustainability/i18n/sustainability.pot
  sustainability/models/carbon_line_origin.py
  sustainability/views/carbon_line_origin.xml
Labels: bot is merging ⏳, needs review

#325 [18.0][MIG] sustainability_hr_expense_report
  sustainability_hr_expense_report/README.rst
  sustainability_hr_expense_report/__init__.py
  sustainability_hr_expense_report/__manifest__.py
  sustainability_hr_expense_report/i18n/fr.po
  sustainability_hr_expense_report/i18n/sustainability_hr_expense_report.pot
  sustainability_hr_expense_report/models/__init__.py
  sustainability_hr_expense_report/models/hr_expense.py
  sustainability_hr_expense_report/pyproject.toml
  sustainability_hr_expense_report/readme/CONTRIBUTORS.rst
  sustainability_hr_expense_report/readme/DESCRIPTION.rst
  sustainability_hr_expense_report/static/description/index.html
  sustainability_hr_expense_report/views/hr_expense.xml
  sustainability_hr_expense_report/views/hr_expense_sheet.xml
Labels: bot is merging ⏳, needs review

#328 [17.0][FIX] sustainability: fix carbon_type determination
  sustainability/models/account_move_line.py
Labels: bot is merging ⏳, needs review

#327 [16.0][BP] back port
  sustainability/models/account_move_line.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_line_origin.py
  sustainability/models/carbon_mixin.py
  sustainability/tests/__init__.py
  sustainability/tests/common.py
  sustainability/tests/test_conversion.py
  sustainability/tests/test_preceeding_order.py
  sustainability/tests/test_vendors_bill.py
  sustainability/views/carbon_line_origin.xml
  sustainability_hr_expense_report/models/hr_expense.py
  sustainability_purchase/models/purchase_order_line.py
  sustainability_purchase/tests/test_purchase.py
Labels: bot is merging ⏳, needs review

#326 [18.0][FP] sustainability*: forward port
  sustainability/models/account_move_line.py
  sustainability/models/carbon_line_mixin.py
  sustainability/models/carbon_line_origin.py
  sustainability/models/carbon_mixin.py
  sustainability/tests/__init__.py
  sustainability/tests/common.py
  sustainability/tests/test_conversion.py
  sustainability/tests/test_preceeding_order.py
  sustainability/tests/test_vendors_bill.py
  sustainability/views/carbon_line_origin.xml
  sustainability_purchase/models/purchase_order_line.py
Labels: bot is merging ⏳, needs review

#330 [FIX] sustainability: add check for empty self in can_compute_carbon_value
  sustainability/models/carbon_mixin.py
Labels: bug, bot is merging ⏳, needs review

#333 [FIX] sustainability: add check for empty self in can_compute_carbon_value
  sustainability/models/carbon_mixin.py
Labels: bot is merging ⏳, needs review

#335 [FIX][#335] sustainability: Fix every ensure_one on carbon_mixin
  sustainability/models/carbon_mixin.py
Labels: bug, easy, bot is merging ⏳, needs review

#339 [17.0][CI] copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .ruff.toml
Labels: bot is merging ⏳, needs review

#334 [FIX] sustainability_employee_commuting: filter employees with contracts by date
  sustainability_employee_commuting/models/res_company.py
Labels: bug, bot is merging ⏳, needs review

#338 [FIX] sustainability_employee_commuting: remote work - EF not set
  sustainability_employee_commuting/models/res_company.py
Labels: bug, bot is merging ⏳, needs review

#341 [16][MIG] sustainability_*: Multiple backport
  sustainability/models/__init__.py
  sustainability/models/account_move.py
  sustainability/models/account_move_line.py
  sustainability/models/carbon_common_mixin.py
  sustainability/models/carbon_factor.py
  sustainability/models/carbon_mixin.py
  sustainability/models/common_mixin.py
  sustainability/models/sustainability_action.py
  sustainability/models/sustainability_action_plan.py
  sustainability/models/sustainability_nomenclature.py
  sustainability/models/sustainability_scenario.py
  sustainability/tests/__init__.py
  sustainability/tests/test_action.py
  sustainability/tests/test_ef_by_weight.py
  sustainability/views/account_analytic_line.xml
  sustainability/views/account_move.xml
  sustainability/views/account_move_line.xml
  sustainability/views/carbon_factor.xml
  sustainability/views/sustainability_action.xml
  sustainability/views/sustainability_action_plan.xml
  sustainability/views/sustainability_scenario.xml
  sustainability_purchase/models/purchase_order.py
  sustainability_purchase/models/purchase_order_line.py
  sustainability_purchase/views/carbon_factor.xml
  sustainability_purchase/views/purchase_order.xml
Labels: bot is merging ⏳, needs review

#346 [FIX][#345] sustainability: Fix from_uom_id not taking in account from account.move.line
  sustainability/models/carbon_factor.py
Labels: bot is merging ⏳, needs review

#348 [16.0][MIG] [FIX][#345] sustainability: Fix from_uom_id not taking in account from account.move.line
  .oca/oca-port/blacklist/sustainability.json
  sustainability/models/carbon_factor.py
Labels: bot is merging ⏳

#354 [IMP] sustainability: Add is invoice line on CLO
  sustainability/models/account_move_line.py
  sustainability/models/carbon_line_origin.py
  sustainability/views/carbon_line_origin.xml
Labels: approved, bot is merging ⏳, needs review

#356 [16.0][FW] [IMP] sustainability: Add is invoice line on CLO
  sustainability/models/account_move_line.py
  sustainability/models/carbon_line_origin.py
  sustainability/views/carbon_line_origin.xml
Labels: bot is merging ⏳, needs review

#357 [FIX] sustainability: Add condition to compute method
  sustainability/models/carbon_factor.py
Labels: needs review

#358 [FIX] sustainability: Fix uncertainty sign
  sustainability/models/account_move.py
  sustainability/tests/common.py
  sustainability/tests/test_carbon_computation.py
  sustainability/tests/test_conversion.py
  sustainability/tests/test_ef_by_weight.py
  sustainability/tests/test_preceeding_order.py
  sustainability/tests/test_vendors_bill.py
Labels: bot is merging ⏳, needs review

#359 [FIX] sustainability: Add condition to compute method
  sustainability/models/account_move.py
  sustainability/models/carbon_factor.py
  sustainability/tests/common.py
  sustainability/tests/test_carbon_computation.py
  sustainability/tests/test_conversion.py
  sustainability/tests/test_ef_by_weight.py
  sustainability/tests/test_preceeding_order.py
  sustainability/tests/test_vendors_bill.py
Labels: merged 🎉, needs review

#360 [16.0][FW] Blacklist of some PRs from 17.0
  .oca/oca-port/blacklist/sustainability.json
Labels: bot is merging ⏳, needs review

#329 [FIX] sustainability,*_purchase: fix autosave
  sustainability/views/account_account.xml
  sustainability/views/product_category.xml
  sustainability/views/product_template.xml
  sustainability/views/res_country.xml
  sustainability_purchase/views/purchase_supplierinfo.xml
  sustainability_purchase/views/res_partner.xml
Labels: approved, bot is merging ⏳
