Repository sustainability-suite/sustainability-odoo, pull requests merged in 2025-04, with the labels that each got.

#395 [FIX] sustainability: uom invoice line weight ef
  sustainability/models/carbon_factor.py
  sustainability/tests/test_ef_by_weight.py
Labels: bug, bot is merging ⏳, needs review

#401 [16.0][FW] Blacklist of some PRs from 17.0
  .oca/oca-port/blacklist/sustainability.json
Labels: bot is merging ⏳

#402 [18.0][FW] [IMP] sustainability: validity date tests
  .oca/oca-port/blacklist/sustainability.json
Labels: needs review

#408 [IMP] sustainability: Add pre-init-hook for larger database
  requirements.txt
  sustainability/__init__.py
  sustainability/__manifest__.py
Labels: merged 🎉, needs review

#411 [17.0][FW] [IMP] sustainability: Add pre-init-hook for larger database
  requirements.txt
  sustainability/__init__.py
  sustainability/__manifest__.py
Labels: merged 🎉, needs review

#415 [FIX] sustainability: create_journal_entry test tour
  eslint.config.cjs
  sustainability/static/src/js/tours/create_journal_entry.js
  sustainability/tests/test_tour.py
Labels: bug, bot is merging ⏳, needs review

#410 [18.0] sustainability_stock: Migration to 18.0
  sustainability_stock/README.rst
  sustainability_stock/__init__.py
  sustainability_stock/__manifest__.py
  sustainability_stock/data/menu_items.xml
  sustainability_stock/i18n/sustainability_stock.pot
  sustainability_stock/models/__init__.py
  sustainability_stock/models/account_move.py
  sustainability_stock/models/carbon_line_mixin.py
  sustainability_stock/models/carbon_line_origin.py
  sustainability_stock/models/res_company.py
  sustainability_stock/models/res_config_settings.py
  sustainability_stock/models/res_partner.py
  sustainability_stock/models/stock_picking.py
  sustainability_stock/models/sustainability_stock_freight_computation.py
  sustainability_stock/pyproject.toml
  sustainability_stock/readme/CONTRIBUTORS.rst
  sustainability_stock/readme/DESCRIPTION.rst
  sustainability_stock/security/ir.model.access.csv
  sustainability_stock/static/description/index.html
  sustainability_stock/tests/__init__.py
  sustainability_stock/tests/common.py
  sustainability_stock/tests/test_stock.py
  sustainability_stock/views/carbon_line_origin.xml
  sustainability_stock/views/res_config_settings.xml
  sustainability_stock/views/res_partner.xml
  sustainability_stock/views/stock_picking.xml
  sustainability_stock/views/sustainability_stock_freight_computation.xml
Labels: bot is merging ⏳, needs review

#398 ➕ Spreadsheet dashboard
  sustainability_spreadsheet_dashboard/README.rst
  sustainability_spreadsheet_dashboard/__init__.py
  sustainability_spreadsheet_dashboard/__manifest__.py
  sustainability_spreadsheet_dashboard/data/dashboards.xml
  sustainability_spreadsheet_dashboard/data/files/co2_dashboard.json
  sustainability_spreadsheet_dashboard/i18n/fr.po
  sustainability_spreadsheet_dashboard/pyproject.toml
  sustainability_spreadsheet_dashboard/readme/CONTRIBUTORS.rst
  sustainability_spreadsheet_dashboard/readme/DESCRIPTION.rst
  sustainability_spreadsheet_dashboard/static/description/index.html
Labels: bot is merging ⏳, needs review

#417 [MIG] sustainability_spreadsheet_dashboard
  sustainability_spreadsheet_dashboard/README.rst
  sustainability_spreadsheet_dashboard/__init__.py
  sustainability_spreadsheet_dashboard/__manifest__.py
  sustainability_spreadsheet_dashboard/data/dashboards.xml
  sustainability_spreadsheet_dashboard/data/files/co2_dashboard.json
  sustainability_spreadsheet_dashboard/i18n/fr.po
  sustainability_spreadsheet_dashboard/i18n/sustainability_spreadsheet_dashboard.pot
  sustainability_spreadsheet_dashboard/pyproject.toml
  sustainability_spreadsheet_dashboard/readme/CONTRIBUTORS.rst
  sustainability_spreadsheet_dashboard/readme/DESCRIPTION.rst
  sustainability_spreadsheet_dashboard/static/description/index.html
Labels: bot is merging ⏳, needs review
